.gitignore, Cargo.lock, build.rs
* Updates `build.rs`:
- Changes `decNumberStatic` to `decNumber_static` because of changes
to upstream.
- Links against `libc++` on macOS and `libstdc++` on Linux.
- Makes C++ linkage explicitly dynamic.
- Adds TODO/explicit build failure for Windows and other platform.
=> Updates ion-c to latest.

build.rs
Cargo requires that build scripts [only modify the contents of the $OUT_DIR folder](https://doc.rust-lang.org/cargo/reference/build-scripts.html#outputs-of-the-build-script), a path which is passed in as an environment variable.
Previously, the build script (`build.rs`) would create a new folder in the ion-c submodule and store its build artifacts there. This caused Cargo to object when it tried to package the crate for publishing.
*Description of changes:*
This PR modifies the build script to create `$OUT_DIR/ion-c/build/release` instead of `./ion-c/build/release` and stores all build artifacts there.
=> ion-c now builds inside $OUT_DIR

.dockerignore, .github/workflows/verify-docker-build.yml, Dockerfile, README.md
Hi there!
I've added a Dockerfile that makes a *relatively small* multi-stage image of the CLI that should be usable cross-platform (only tested on macOS so far but no reason to believe it would fail on Windows/Linux).
I'm interested in contributing something more meaningful (i.e. tests for #10 when I have a little more time) but wanted to send this for now. I also understand if you don't want to merge since it *does* sadly change your repo stats from  100% to 99.1% Rust, 0.9% Dockerfile :smile:.
Question for maintainers:
- This builds and appears to run with latest release of Rust as of 10/22, version 1.56. Should this be pinned to another Rust version?
- I haven't looked too closely into [amzn/ion-c](https://github.com/amzn/ion-c) CMake files but the only C/C++ build dependencies on …
=> Add Dockerfile and instructions

Cargo.lock, Cargo.toml
* Upgrades the crate to edition 2021
* Bumps the version from v0.1.1 to v0.2.0
=> Set edition to 2021 and bump to v0.2.0

src/bin/ion/commands/beta/mod.rs, src/bin/ion/commands/beta/schema/mod.rs, src/bin/ion/main.rs
Starting in Rust 1.59, calls to the `unreachable!` macro no longer
accept string variables as their first parameter. This brings their
behavior in line with macros like `println!`, `format!`, and `write!`.
See: https://github.com/rust-lang/rust/issues/94475
=> Fixes unreachable! calls in Rust 1.59+

.github/workflows/build.yml, README.md
*Issue #, if available:*
* related to #5 but was really fixed in #25 
*Description of changes:*
Another very minor CI change after seeing the `ion-c` dependency was removed (:tada:). Wanted address some of the old TODOs mentioned in previous PR.
* add Windows build after testing in fork
* enable parallel tests, run rustfmt in CI
* remove mention of C toolchain requirements from README
Had originally added `-- --test-threads=1` since tests were flakey when there was the `ion-c` dependency. Running locally and in CI showed this is no longer needed.
=> Add Windows build again, remove LLVM, Clang CI setup

Cargo.lock, Cargo.toml, src/bin/ion/commands/beta/count.rs, src/bin/ion/commands/beta/inspect.rs, src/bin/ion/commands/beta/mod.rs, src/bin/ion/commands/beta/primitive.rs, src/bin/ion/commands/beta/schema/validate.rs, src/bin/ion/commands/dump.rs
* Upgrades dependency on `ion-rs` to v0.12.0
* Updates `ion-schema` to v0.4.0, which uses ion-rs v0.12.0
* Modifies the way encoding lengths are calculated following
a change in the v0.12.0 binary reader API.
* Fixes issue #17; nested containers now have a trailing comma
where necessary.
* Adds a `beta count` command that prints the number of top-level
values in a given stream.
* Adds a `beta primitive` command that prints the decimal and
hex representations of a value's primitive encoding
(For example: the VarUInt encoding of 527.)
=> Upgrades ion-rs, adds beta 'count' and 'primitive' commands

README.md, src/bin/ion/commands/beta/inspect.rs
This PR depends on #30. Once 30 has been merged, this one will be rebased against `master`.
------
PR #28 attempted to fix #17, but overcorrected.
Previously, nested containers would not be followed by a delimiting `,`:
```
[
{}
{}
{}
]
```
Following #28, this was fixed:
```
[
{},
{},
{},
]
```
but it also added commas after _top-level containers_:
```
$ion_symbol_table::{
// ....
},
{
foo: true
},
{
bar: 5
},
```
which is incorrect.
This PR fixes that behavior.
=> Top-level containers are no longer followed by a comma

Cargo.lock, Cargo.toml, src/bin/ion/commands/beta/inspect.rs, src/bin/ion/commands/dump.rs, tests/cli.rs
Also adopt ion-rs 0.14.0
*Description of changes:*
This adds support for the new `lines()` formatter in `ion-rs`: https://github.com/amzn/ion-rust/blob/main/src/text/raw_text_writer.rs#L34-L52
This is helpful for working with line-delimited text-oriented tooling (`sort`, `grep`, `uniq` etc.). 
*Testing:*
Comparing the various text formats. 
```plain
❯ cat c.json | cargo -q run dump --format text
```
```plain
[1, 2, 3] [4, 5, 6]
```
```plain
❯ cat c.json | cargo -q run dump --format lines
```
```plain
[1, 2, 3]
[4, 5, 6]
```
```plain
❯ cat c.json | cargo -q run dump --format pretty
```
```plain
[
1,
2,
3
]
[
4,
5,
6
]
```
=> Add a new 'lines' text format

Cargo.lock, Cargo.toml, src/bin/ion/commands/beta/count.rs, src/bin/ion/commands/beta/inspect.rs, src/bin/ion/commands/beta/mod.rs, src/bin/ion/commands/beta/primitive.rs, src/bin/ion/commands/beta/schema/load.rs, src/bin/ion/commands/beta/schema/mod.rs, src/bin/ion/commands/beta/schema/validate.rs, src/bin/ion/commands/dump.rs, src/bin/ion/commands/mod.rs, src/bin/ion/main.rs
The `ion-cli` now uses the latest major version of `clap`.
=> Upgrades `clap` from 2.x to 4.x

Cargo.lock, Cargo.toml, README.md, src/bin/ion/commands/beta/schema/validate.rs
*Description of changes:*
This PR works on updating `ion-schema-rust` to latest version `0.6.0` and adds `schema` sub command guidelines in README.
=> Updates `ion-schema-rust` to `v0.6.0`

src/bin/ion/commands/beta/head.rs, src/bin/ion/commands/beta/mod.rs, src/bin/ion/commands/dump.rs, src/bin/ion/commands/mod.rs, tests/cli.rs
N/A
This PR adds an option `head` to `ion-cli` tool, which allows to get the first specific number of top-level data in the input stream.
Here is the example of print out the fist 2 top-level value of testData.ion:
`ion beta head --number 2 --format lines testData.ion`
Results:
```
{foo: bar, abc: [123, 456]}
{foo: baz, abc: [420d-1, 4.3e1]} 
```
Original data testData.ion:
```
{
foo: bar,
abc: [123, 456]
}
{
foo: baz,
abc: [42.0, 43e0]
}
{
foo: bar,
test: data
}
{
foo: baz,
type: struct
}
```
=> Adds 'head' option to allow user get the first specific number of ion values of the input file.

Cargo.lock, Cargo.toml, src/bin/ion/commands/beta/inspect.rs
`ion-rs` v0.18.0 had a bug in the raw bytes accessors for the `SystemReader` that caused it to panic after reading more than ~4KB of data. [v0.18.1](https://github.com/amazon-ion/ion-rust/pull/566) addressed that problem.
This PR upgrades our dependency on `ion-rs` to v0.18.1, allowing the `inspect` command to use the latest `ion-rs`.
----
=> Upgrades ion-rs to v0.18.1

src/bin/ion/commands/beta/count.rs, src/bin/ion/commands/beta/from/json.rs, src/bin/ion/commands/beta/from/mod.rs, src/bin/ion/commands/beta/head.rs, src/bin/ion/commands/beta/inspect.rs, src/bin/ion/commands/beta/mod.rs, src/bin/ion/commands/beta/primitive.rs, src/bin/ion/commands/beta/schema/load.rs, src/bin/ion/commands/beta/schema/mod.rs, src/bin/ion/commands/beta/schema/validate.rs, src/bin/ion/commands/beta/to/json.rs, src/bin/ion/commands/beta/to/mod.rs, src/bin/ion/commands/dump.rs, src/bin/ion/commands/mod.rs, src/bin/ion/main.rs, tests/cli.rs
This PR introduces two traits:
1. `IonCliCommand`, which captures functionality common to all commands/namespaces.
2. `WithIonCliArgument`, which adds extension methods to `clap`'s `Command` type, making it much easier for commands to use the same flag configurations as other commands.
This eliminates a large amount of the copy/pasting that was proliferating across subcommands.
----
=> Command traits

src/bin/ion/commands/beta/mod.rs, src/bin/ion/commands/beta/symtab/filter.rs, src/bin/ion/commands/beta/symtab/mod.rs
This adds a command (`beta symtab filter`) that strips all user data out of the input stream and writes the remaining symbol tables to output. If you use the `--lift` flag, the symbol tables will be stripped of their `$ion_symbol_table` annotation, lifting them into user-level structs that are easier to view and pipe to other commands downstream.
For the moment, this only supports binary input but that's where symbol tables are most commonly leveraged anyway.
----
=> Adds command to filter user data, leaving symtabs

src/bin/ion/main.rs
Without this, using `ion-cli` in a pipeline which truncates the output can result in unwanted error output to stderr, e.g.:
```plain
❯ ion dump foo.ion | grep "^  timestamp" | cut -w -f 3 | cut -c 2-20 | head -2
```
```plain
2023-07-31T23:11:36
2023-07-31T23:11:36
Error: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }
Caused by:
Broken pipe (os error 32)
```
By handling `BrokenPipe` gracefully (i.e. ignoring it), we instead see:
```plain
❯ ion dump foo.ion | grep "^  timestamp" | cut -w -f 3 | cut -c 2-20 | head -2
```
```plain
2023-07-31T23:11:36
2023-07-31T23:11:36
```
----
=> Handle BrokenPipe gracefully

.gitignore, Cargo.lock, Cargo.toml, Dockerfile, src/bin/ion/commands/beta/head.rs, src/bin/ion/commands/dump.rs, tests/cli.rs
n/a
This change extends the `dump` subcommand to be able to automatically detect gzip- and zstd-compressed Ion files and stdin streams and transparently decompress them. A new option was added, `--no-auto-decompress`, to disable this automatic behavior and decode the original input directly.
Added a new test, `cargo test` passes. No noticeable performance degradation despite some extra dynamic dispatch.
----
=> dump: autodetect and decompress gzip and zstd

Cargo.toml, src/bin/ion/commands/beta/inspect.rs, src/bin/ion/commands/mod.rs
Inspired by the CLI Guidelines (https://clig.dev/#output); also, I always pipe `ion beta inspect` to less, but usually after I've forgotten to do that and blown away my terminal by trying to inspect a huge file.
This PR directs output to the pager specified by the `PAGER` environment variable, or `less -FIRX` if the environment variable is not set. Note: a pager is not used if the output is not a TTY.
`less -FIRX` has the following behavior:
* does not page if the content fills one screen (i.e., for small streams, the behavior does not change)
* ignores case when you search
* enables color and formatting (which we don't currently use, but could)
* leaves the contents on the screen when `less` quits
Currently a pager is not used on Windows because the …
=> Directs output of 'inspect' to a pager (default: 'less').

src/bin/ion/commands/beta/generate/generator.rs, src/bin/ion/commands/beta/generate/mod.rs, src/bin/ion/commands/beta/generate/templates/java/class.templ, src/bin/ion/commands/beta/generate/templates/rust/import.templ, src/bin/ion/commands/beta/generate/templates/rust/mod.templ, src/bin/ion/commands/beta/generate/templates/rust/struct.templ, src/bin/ion/commands/beta/generate/utils.rs, tests/cli.rs
This PR works on adding set-up changes for integration roundtrip tests on generated code
- Adds some changes for struct templates, that were resulting in specific errors with roundtrip testing
- Replaces `to_string()?` with `to_str()?.to_string()`. (`to_string()` would return a raw string e.g. "\"hello\"" whereas `to_str()` returns a string value as `"hello"`)
- Adds `isl_type_name` property in `Field` this helps store `symbol` as Rust/Java string but when writing it as Ion it will use `write_symbol` using `write_{{ field.isl_type_name}}`.
- Add a namespace option for java code generation (This option is only required when `--language` option is set as `java`).
- Adds changes to use only a single module with all generated data models in Rust. Generated module is named as …
=> Adds changes for setting up integration roundtrip tests for generated code

code-gen-projects/java/code-gen-demo/build.gradle.kts, code-gen-projects/rust/code-gen-demo/build.rs, tests/code-gen-tests.rs
This PR is a follow up on requested changes to #95.
----
=> Adds changes for code generation tests configuration

code-gen-projects/input/bad/nested_struct/mismatched_type.ion, code-gen-projects/input/bad/struct_with_fields/mismatched_sequence_element.ion, code-gen-projects/input/bad/struct_with_fields/mismatched_type.ion, code-gen-projects/input/good/nested_struct/empty_values.ion, code-gen-projects/input/good/nested_struct/valid_fields.ion, code-gen-projects/input/good/nested_struct/valid_unordered_fields.ion, code-gen-projects/input/good/struct_with_fields/empty_values.ion, code-gen-projects/input/good/struct_with_fields/valid_fields.ion, code-gen-projects/input/good/struct_with_fields/valid_unordered_fields.ion, code-gen-projects/input/struct_with_fields.ion, code-gen-projects/java/code-gen-demo/build.gradle.kts, code-gen-projects/java/code-gen-demo/src/test/java/org/example/CodeGenTest.java, code-gen-projects/rust/code-gen-demo/Cargo.lock, code-gen-projects/rust/code-gen-demo/Cargo.toml, code-gen-projects/rust/code-gen-demo/src/lib.rs, code-gen-projects/schema/struct_with_fields.isl, src/bin/ion/commands/beta/generate/generator.rs, src/bin/ion/commands/beta/generate/templates/java/class.templ, src/bin/ion/commands/beta/generate/templates/rust/struct.templ, src/bin/ion/commands/beta/generate/utils.rs, tests/cli.rs
This PR adds read-write API generation support for Java.
This example uses schema `struct_with_fields` from `code-gen-projects/schema/`.
_Note: The generated code has been formatted here and actual code might have extra lines and tabs._
```java
public static StructWithFields readFrom(IonReader reader) {
AnonymousType2 c = null;
int b = 0;
String a = null;
double d = 0;
reader.stepIn();
while (reader.hasNext()) {
reader.next();
String fieldName = reader.getFieldName();
switch (fieldName) {
case "C":
c = AnonymousType2.readFrom(reader);
break;
case "B":
b = reader.intValue();
break;
case "A":
a = reader.stringValue();
break;
case "D":
d = reader.doubleValue();
break;
default:
throw new IonException("Can not read field name:" + fieldName +
" for StructWithFields as it doesn't exist in the …
```
=> Adds read-write API generation support for Java code generation

code-gen-projects/README.md
This PR adds a README file for `code-gen-projects` directory which includes example Java and Rust projects which uses `ion-cli` to generate code and has tests defined for the generated code.
----
=> Adds README for code-gen-projects

Cargo.lock, Cargo.toml, src/bin/ion/commands/beta/count.rs, src/bin/ion/commands/beta/generate/utils.rs, src/bin/ion/commands/beta/inspect.rs, src/bin/ion/commands/beta/mod.rs, src/bin/ion/commands/beta/primitive.rs, src/bin/ion/commands/beta/symtab/filter.rs, src/bin/ion/commands/beta/to/json.rs, src/bin/ion/commands/dump.rs, src/bin/ion/commands/mod.rs, src/bin/ion/file_writer.rs, src/bin/ion/main.rs, tests/cli.rs, tests/code-gen-tests.rs
* Upgrades the `ion-cli`'s dependency on `ion_rs` from `v1.0.0-rc.2` to `v1.0.0-rc.5`.
* Removes our dependency on `memmap`; all commands are now streaming.
* Removes hack to add newlines between per-file outputs from `dump`.
* Overhauls the `inspect` command to take advantage of new tooling access APIs in the streaming reader. The new version:
* shows opcodes and `VarUInt` lengths in a style that is distinct from that of the body of the value
* uses Unicode box drawing to render its table
* colors annotations and field names in the text Ion column
* shows the symbol ID assigned to each string in a local symbol 
Fixes issues #34 and #36.
----
=> Upgrade to `ion_rs` dependency to v1.0.0-rc.5

src/bin/ion/commands/beta/mod.rs, src/bin/ion/commands/inspect.rs, src/bin/ion/commands/mod.rs, src/bin/ion/main.rs
Also expands the `--help` text to indicate that its output is not guaranteed to be stable for the purposes of machine readability.
----
=> Promotes `inspect` out of beta

src/bin/ion/auto_decompress.rs, src/bin/ion/commands/beta/count.rs, src/bin/ion/commands/beta/from/json.rs, src/bin/ion/commands/beta/head.rs, src/bin/ion/commands/beta/symtab/filter.rs, src/bin/ion/commands/beta/to/json.rs, src/bin/ion/commands/cat.rs, src/bin/ion/commands/dump.rs, src/bin/ion/commands/inspect.rs, src/bin/ion/commands/mod.rs, src/bin/ion/input.rs, src/bin/ion/main.rs, src/bin/ion/output.rs, src/bin/ion/transcribe.rs, tests/cli.rs
-----
This PR introduces a `CommandIo` type that provides a centralized implementation of input and output file/stream setup. Individual commands are no longer responsible for detecting I/O errors, configuring decompression, or setting up `termcolor`'s output streams.
It also:
* Makes `dump` a deprecated alias for the command's new name: `cat`.
* Factors out the transcription logic shared by both `head` and `cat`.
* Adds a `CommandInput` type that remembers the name of the input stream and what type of compression it detected.
* Adds a `CommandOutput` type that statically dispatches over `File`/`StdOut` and supports `termcolor`.
----
=> Centralizes I/O setup, adds `cat` alias for `dump` command

code-gen-projects/schema/nested_struct.isl, code-gen-projects/schema/struct_with_fields.isl, src/bin/ion/commands/beta/generate/context.rs, src/bin/ion/commands/beta/generate/generator.rs, src/bin/ion/commands/beta/generate/utils.rs, tests/code-gen-tests.rs
This PR works on adding support for struct with both `type` and `fields` constraint.
- Modified `map_constraint_to_abstract_data_type` to add support for `type: struct`.
- Currently implementation returns an error if only `type: struct` was used without `fields` constraints.
- Generated code remains same as per `fields` constraint.
Modified current tests and add an invalid test case for only `type:struct` constraint inside a type def.
----
=> Adds support for struct with both `type` and `fields` constraint

src/bin/ion/commands/beta/generate/generator.rs, src/bin/ion/commands/beta/generate/mod.rs, src/bin/ion/commands/beta/generate/templates/mod.rs
This PR works on adding template resources as constants. This change makes the template files as string constants which can be used by the binary crate.
- Adds template modules `rust` and `java` that contains all string constants pointing to corresponding template.
- Changed `tera` to be instantiated as `default` and then all these constants are used to add raw templates to `tera`.
Tested with `brew test` to make sure that `generate` subcommand has access to templates.
Related PR: https://github.com/amazon-ion/homebrew-ion-cli/pull/7
----
=> Adds template resources as constants

README.md, code-gen-projects/README.md
This PR adds changes to README for installing experimental features (currently includes only code generation's `generate` subcommands)
----
=> Adds README changes for installation of experimental features

src/bin/ion/commands/beta/generate/mod.rs, src/bin/ion/commands/beta/generate/model.rs, src/bin/ion/commands/beta/generate/utils.rs
This PR is adds a new model for code generator to make it simpler for getting information on nested types and element type in sequence.
- `DataModel` is a the new abstract data type that will be used by code generator to render templates.
- `CodeGenType` is similar to the prior `AbstractDataType` but more informative includes fields details and element type details.
- `FullyQualifiedTypeName` and `FullyQualifiedTypeReference` are used for storing all levels of the fully qualified name of the type.
- This PR only introduces the model but doesn't yet use it in the implementation.
----
=> Adds a new model for code generator

src/bin/ion/auto_decompress.rs
This PR changes the GzDecoder used for decompressing gzip'd inputs to a MultiGzDecoder in order to handle multi-member gzip files.
Pre-PR (using homebrew'd ion-cli):
```
glitch@147dda5e5395 ~/C/ion-cli> ion dump user-data.ion.gz | ion beta count
1213
```
Post-PR:
```
glitch@147dda5e5395 ~/C/ion-cli> cargo run --release dump user-data.ion.gz | ion beta count
Finished release [optimized] target(s) in 0.19s
Running `target/release/ion dump user-data.ion.gz`
2541
glitch@147dda5e5395 ~/C/ion-cli> 
```
----
=> Use MultiGzDecoder to support multi-member gzip files

src/bin/ion/commands/cat.rs, src/bin/ion/commands/command_namespace.rs, src/bin/ion/commands/count.rs, src/bin/ion/commands/from/json.rs, src/bin/ion/commands/from/mod.rs, src/bin/ion/commands/generate/mod.rs, src/bin/ion/commands/head.rs, src/bin/ion/commands/inspect.rs, src/bin/ion/commands/mod.rs, src/bin/ion/commands/schema/mod.rs, src/bin/ion/commands/schema/validate.rs, src/bin/ion/commands/symtab/filter.rs, src/bin/ion/commands/symtab/mod.rs, src/bin/ion/commands/to/json.rs, src/bin/ion/commands/to/mod.rs, src/bin/ion/main.rs
Follow up for #128.
* Changes the defaults of `IonCliCommand`'s `is_stable()` to `false` and `is_porcelain()` to `true`.
* Creates a new trait for namespaces so that they are stable and plumbing by default. Also has the benefit of extracting the namespace logic out of `IonCliCommand`.
----
=> Refactor namespace logic out of default command logic

.github/workflows/build.yml, Cargo.toml, src/bin/ion/commands/mod.rs, src/bin/ion/main.rs, tests/cli.rs, tests/code-gen-tests.rs
None
It is redundant to have the `-X` flag for unstable commands and a cargo feature flag for an unstable command. This removes the cargo feature flag.
----
=> Removes cargo feature flag for code-gen

.github/workflows/build.yml, Cargo.lock, Cargo.toml, Dockerfile, src/bin/ion/commands/inspect.rs, src/bin/ion/commands/mod.rs
* Upgrades the `ion-cli`'s dependency on `ion-rs` to [`v1.0.0-rc.7`](https://github.com/amazon-ion/ion-rust/releases/tag/v1.0.0-rc.7).
* Ion 1.1 value literals are recognized and their encodings displayed in the expected fashion.
* Ion 1.1 macro invocations (e-expressions) at the top level have their encodings displayed; the ephemeral values they produce follow them in a dimmed font.
* E-expression arguments have comments showing which macro parameter they correspond to
* Ephemeral values use the binary encoding column to indicate which parameter variable was backing the corresponding application value.
* This implementation does not yet support displaying e-expressions nested inside containers.
----
_**By submitting this pull request, I confirm that my contribution is made under the …
=> Adds support for Ion 1.1 to `inspect`

Cargo.toml
Prior to this PR, our `lowcharts` dependency had a version of `*` (wildcard/latest). This is not permitted for binaries published via `cargo` as it leads to breakages when the dependencies release new major versions.
This patch sets its version to the latest available.
----
=> Set a version for `lowcharts` dependency

code-gen-projects/schema/scalar.isl, src/bin/ion/commands/generate/generator.rs, src/bin/ion/commands/generate/model.rs, src/bin/ion/commands/generate/templates/java/scalar.templ, tests/cli.rs
This PR works on adding new model changes following up on #135. This Pr only contains changes for `Structure` (does not contains changes for model variants `Sequence` and `Scalar`). This PR disables Rust support until the entire functionality for the new model change is supported and uses feature branch `new-model-changes` as target.
* Generator changes:
* Adds `build_wrapped_scalar_from_constraints` which is used for constructing named scalar data type as data model.
* Adds `build_scalar_from_constraints` which is used for constructing nested scalar data type as data model. (Doesn't have a name)
* Adds `is_nested` flag in `convert_isl_type_def_to_data_model_node` which can be used to either call wrapped sclar or scalar ADT construction.
* Modified `structure` construction to move the …
=> Adds new model changes for scalar

Cargo.lock, Cargo.toml, src/bin/ion/commands/generate/generator.rs, src/bin/ion/commands/generate/model.rs, src/bin/ion/commands/inspect.rs, src/bin/ion/commands/schema/validate.rs, src/bin/ion/commands/stats.rs, tests/code-gen-tests.rs
None.
Updates `ion-rs` and `ion-schema` crates to the latest versions. There's also a bunch of clippy fixes that ended up here too.
----
=> Update ion-schema and ion-rs dependencies

src/bin/ion/commands/complaint.rs, src/bin/ion/commands/mod.rs, src/bin/ion/commands/stats.rs, src/bin/ion/main.rs
* Commands now support a "regular" `about`, and a `long_about`. This allows us to put the shorter one into the listing of subcommands and the longer one can go in the more detailed help.
* Reformat the help messaging for `ion stats` so that it wraps at a similar line length as the other commands.
* Adds a comment to the end of the top-level help directing users to open an issue in `ion-cli` if they are experiencing a problem with the CLI.
* Adds a little surprise for when you are upset with Ion. 
----
=> Improve help messages

src/bin/ion/ansi_codes.rs, src/bin/ion/commands/complaint.rs, src/bin/ion/commands/schema/validate.rs, src/bin/ion/main.rs
None
* Adds a module with ansi code constants that can be imported and used in a `format!()` string. See `validate.rs` for example usage.
* Adds more help documentation to the `validate` command.
* Fixes a clippy warning in `complaint.rs`.
* Adds a new "report" output format for the validate command. "Report" is a rather vague name, so if you have a better idea, please share it with me.
Example usage and output (but `ok` is green and `FAILED` is red, just like the `cargo test` report).
```
❯ cargo run -- schema -X validate -R 'document' **/*.ion
code-gen-projects/input/good/scalar/empty_value.ion ... ok
code-gen-projects/input/good/scalar/valid_value.ion ... ok
code-gen-projects/input/good/sequence/empty_sequence.ion ... FAILED
code-gen-projects/input/good/sequence/valid_elements.ion ... …
```
=> Adds 'report' output for ion schema validate

Cargo.lock, Cargo.toml
* Updates to use the latest version of `ion-schema`.
* Bumps version so we can release all of the latest and greatest `ion schema validate` improvements.
----
=> Update ion-schema dependency; bump version to 0.8.0

Cargo.lock, Cargo.toml, code-gen-projects/input/bad/sequence_with_enum_element/invalid_value.ion, code-gen-projects/input/good/sequence_with_enum_element/valid_value.ion, code-gen-projects/java/code-gen-demo/src/test/java/org/example/CodeGenTest.java, code-gen-projects/schema/sequence_with_enum_element.isl, src/bin/ion/commands/generate/generator.rs, src/bin/ion/commands/generate/mod.rs, src/bin/ion/commands/generate/model.rs, src/bin/ion/commands/generate/templates/java/class.templ, src/bin/ion/commands/generate/templates/java/enum.templ, src/bin/ion/commands/generate/templates/java/scalar.templ, src/bin/ion/commands/generate/templates/java/sequence.templ, src/bin/ion/commands/generate/templates/java/util_macros.templ, src/bin/ion/commands/generate/templates/rust/scalar.templ, src/bin/ion/commands/generate/templates/rust/sequence.templ, src/bin/ion/commands/generate/templates/rust/struct.templ, src/bin/ion/commands/generate/utils.rs
This PR fixes namespace for nested sequence types and adds support for nested types in sequence and scalar templates.
- [Modified util_macros.templ to use fully-qualified_type_name](https://github.com/amazon-ion/ion-cli/commit/fd67723354c05ae6164214753feee3f794136e4c)
- [Modified fully_qualified_type_ref method to return `FullyQualifiedTypeReference`](https://github.com/amazon-ion/ion-cli/commit/03e3c7ece33ef246d02eaa4298e9fb1732064e1a)
- Previously this returned `Option<FullyQualifiedTypeReference>`
- [Modifies add_namespace and reset_namespace](https://github.com/amazon-ion/ion-cli/commit/fede33b2bbd97b3f7acef16c82b5f0b06fc1c8d9)
* Adds check for last value to verify if its module or type name
* Adds check for empty namespace
- [Modifies generator for sequence type …
=> Adds namespace fix for nested sequence and adds support for nested types in Sequence and Scalar ADT

code-gen-projects/java/code-gen-demo/src/test/java/org/example/CodeGenTest.java, src/bin/ion/commands/generate/generator.rs
This PR works on changing how nested types are named. Nested types are now being named based on the context where they are defined. (i.e. either a field name or predefined name `Element`).
Generated code in Java can be found [here](https://gist.github.com/desaikd/07cf35ce97b52db45de62e5463b61bcd).
- [Modifies naming nested types](https://github.com/amazon-ion/ion-cli/commit/958caf7f4ef38a49092f22eccfd35712ce901142)
* If the nested type is within a struct then name will be based on field
name
* If the the nested type is within a sequence them name will be
predefined string `Element`
- [Adds tests for nested type naming change](https://github.com/amazon-ion/ion-cli/commit/59d95111ec1f87b859d8835a7d3cb4a916fd9e7a)
Adds test changes for using these new names for nested types.
----
_**By …
=> Adds changes for nested type naming

src/bin/ion/commands/inspect.rs, src/bin/ion/commands/mod.rs, src/bin/ion/commands/primitive.rs, src/bin/ion/hex_reader.rs, src/bin/ion/main.rs
None.
The `--hex` option can act as a flag, telling `inspect` to assume that the input is a sequence of hexadecimal pairs. It can also accept a value (e.g. `--hex="e0 01 00 ea"`), in which case it will ignore any other input and inspect the value given for the hex option.
To support this...
* `CommandIo` has been updated to allow using `CommandOutput` without also using `CommandInput`
* Added a `HexReader` that wraps another reader and translates from hex digit string to `u8`s.
Other changes...
* I enabled `wrap-help` in a prior PR, so I reformatted all the help text in `inspect` to take advantage of the automatic wrapping.
* Fix spelling mistake in `primitive` command.
----
_**By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …
=> Adds --hex option to inspect

README.md, code-gen-projects/README.md, code-gen-projects/java/code-gen-demo/build.gradle.kts, code-gen-projects/rust/code-gen-demo/build.rs, src/bin/ion/commands/generate/mod.rs, tests/cli.rs
This PR works on adding README change and CLI options change for code generation.
- [Adds README changes](https://github.com/amazon-ion/ion-cli/commit/e60f854959216b4dede1dcc1fa72c0ac4cd0e3a6)
- [Adds changes for generate subcommand options](https://github.com/amazon-ion/ion-cli/commit/23373d7da7def5c0a9ab09d92f5997b78a0f8905)
- changes CLI options for `generate` subcommand similar to schema subcommand.
----
=> Adds som README and CLI option changes for code generation

README.md
None
Removes a section of the README that isn't needed any more.
----
=> Removes unnecessary section from README

Cargo.lock, Cargo.toml, src/bin/ion/commands/generate/generator.rs, src/bin/ion/commands/hash.rs, src/bin/ion/commands/inspect.rs, src/bin/ion/commands/mod.rs, src/bin/ion/commands/schema/validate.rs, src/bin/ion/commands/symtab/filter.rs, src/bin/ion/hex_reader.rs, src/bin/ion/output.rs
Depends on the version of `ion-rust` in amazon-ion/ion-rust#885.
----
=> Shows e-exprs inside container literals, delimited END

src/bin/ion/commands/inspect.rs
PR #186 added rendering of delimited `END` bytes for container values, but didn't add it for e-expression argument groups. This patch adds that functionality.
----
=> Show closing byte of delimited eexp arg groups

src/bin/ion/commands/stats.rs
- Also adds a `--count` option for simpler output
----
=> Make `stats` resilient to incomplete streams

Cargo.lock, Cargo.toml, src/bin/ion/commands/jq.rs, src/bin/ion/commands/mod.rs, src/bin/ion/main.rs
Lays the groundwork for an `ion jq` command.
This PR adds a dependency on the `jaq` crate, which provides a `jq` engine, and implements the necessary traits for the `Element` type.  
There are many `todo!()`s left to implement to support `jq` features like math operations. However, many basic commands work:
There are plenty of open questions around which `jq` flags to support, what the default expression should be, etc.
----
=> Adds `jq` command

src/bin/ion/commands/cat.rs, src/bin/ion/commands/hash.rs, src/bin/ion/commands/head.rs, src/bin/ion/commands/inspect.rs, src/bin/ion/commands/jq.rs, src/bin/ion/commands/mod.rs, src/bin/ion/commands/schema/validate.rs, src/bin/ion/commands/stats.rs, src/bin/ion/commands/symtab/filter.rs, src/bin/ion/commands/to/json.rs, src/bin/ion/output.rs
=> Adds helpers to `CommandOutput` to deal with output format&encoding

src/bin/ion/commands/jq.rs
Dissimilar numeric types can be used in math operations, with the rules:
1. Operations with `int` and `decimal` => `decimal`
2. Operations with `float` and `int` => `float`
3. Operations with `float` and `decimal` => `float`
Examples:
Given `alias iq='cargo -q run -- -X jq --slurp'`:
> As well as normal arithmetic subtraction on numbers, the `-` operator can be used on arrays to remove all occurrences of the second array's elements from the first array.
| type | input | output |
|--------|--------|--------|
| integer | `echo '1 1' \| iq '.[0] - .[1]'` |  `0` |
| float | `echo '1e0 1e0' \| iq '.[0] - .[1]'` |  `0e0` |
| decimal | `echo '1.0 1.0' \| iq '.[0] - .[1]'` |  `0.0` |
| list | `echo '[1, 2] [2]' \| iq '.[0] - .[1]'` |  `[1,]` |
| sexp | `echo '(1 2) (2)' \| iq '.[0] - .[1]'` | …
=> Implement `-`, `*`, `/`, `%` for `ion jq`

.gitignore, src/bin/ion/commands/cat.rs, src/bin/ion/commands/from/json.rs, src/bin/ion/commands/head.rs, src/bin/ion/commands/mod.rs, src/bin/ion/commands/stats.rs, src/bin/ion/commands/structural_recursion.rs, src/bin/ion/commands/timestamp_conversion.rs, src/bin/ion/commands/to/json.rs, src/bin/ion/transcribe.rs, tests/cli.rs
Added the `--detect-timestamps`/`-t` flag to the `from json` command, which preserves the timestamp data type when converting an Ion value to JSON and back to Ion.
The timestamp detection and conversion logic is implemented in the `convert_timestamps` function, which performs two checks:
`is_timestamp_like` - A heuristic filter that quickly identifies potential timestamp strings to avoid unnecessary processing of non-timestamp values
`ion_rs::IonType::Timestamp` - Uses Ion-rust's implementation to validate and convert valid timestamp strings back to Ion timestamp types
The implementation uses an optional mapper approach in the transcribe module, where:
When `-t` flag is present: Each Ion element is processed through `convert_timestamps`
When `-t` flag is absent: Elements are written …
=> Added --detect-timestamps flag to preserve Ion timestamps during JSON roundtrip
