build.rs
src/bin/ion/commands/beta.rs
src/bin/ion/commands/mod.rs

Implemented beta command.
details: https://github.com/cheqianh/ion-cli/pull/1

Implemented beta command.

---

Cargo.lock
Cargo.toml

Version bump in anticipation of a new release.

Version bump to v0.3.0

---

Cargo.lock
Cargo.toml

Version bump in preparation for the release of v0.4.0.

Version bump to v0.4.0

---

README.md

I added `cargo install` instructions, examples of how to convert between text and binary, and how to use the `inspect` subcommand.

Added examples to README

---

README.md

Adds `brew` installation instructions and a table of contents to `README.md`.

Adds brew install, table of contents to README

---

Dockerfile

Update Rust to v1.64 in Dockerfile
----

Update Rust to v1.64 in Dockerfile

---

Cargo.lock
Cargo.toml
Dockerfile
src/bin/ion/commands/beta/inspect.rs
src/bin/ion/commands/beta/schema/validate.rs
src/bin/ion/commands/beta/to.rs
src/bin/ion/commands/dump.rs
tests/cli.rs

Dependency upgrades:
* `ion-rs`: 0.17.0 -> 0.18.0
* `tempfile`: 3.2.0 -> 3.5.0
* `rstest`: 0.10.0 -> 0.17.0
----

Upgrade dependencies

---

Cargo.toml

Version bump to v0.5.0

---

Cargo.lock
Cargo.toml
src/bin/ion/commands/beta/inspect.rs
src/bin/ion/commands/beta/primitive.rs
src/bin/ion/commands/beta/schema/validate.rs
src/bin/ion/commands/beta/symtab/filter.rs
src/bin/ion/commands/beta/to/json.rs
src/bin/ion/main.rs
tests/cli.rs

Upgrade ion-rs dependency to v1.0.0-rc2

---

Cargo.toml

Version bump to v0.5.1

---

Cargo.lock
Cargo.toml

Version bump to v0.6.0

---

Cargo.lock
Cargo.toml

Version bump to v0.6.1

---

src/bin/ion/commands/beta/generate/generator.rs
src/bin/ion/commands/beta/generate/templates/mod.rs

This PR works on adding changes for updating template resources. Follow-up on #111 
----

Adds changes for updating template resources

---

code-gen-projects/README.md

This PR adds changes to README on how to run tests for demo code gen projects.
* Adds information about the already defined tests in both java and rust projects
* Adds instructions on how to run the tests for java and rust projects
----

Adds changes to README on how to run tests for demo code gen projects

---

Cargo.lock
Cargo.toml
src/bin/ion/commands/generate/model.rs

This PR works on adding builders to the code gen model and add tests for it.
----

Adds changes for builder on the code gen model

---

code-gen-projects/input/bad/struct_with_fields/missing_required_fields.ion
code-gen-projects/input/good/nested_struct/valid_optional_fields.ion
code-gen-projects/input/good/struct_with_fields/valid_optional_fields.ion
code-gen-projects/java/code-gen-demo/src/test/java/org/example/CodeGenTest.java
code-gen-projects/rust/code-gen-demo/src/lib.rs
code-gen-projects/schema/struct_with_fields.isl
src/bin/ion/commands/generate/generator.rs
src/bin/ion/commands/generate/mod.rs
src/bin/ion/commands/generate/model.rs
src/bin/ion/commands/generate/templates/java/class.templ
src/bin/ion/commands/generate/templates/java/nested_type.templ
src/bin/ion/commands/generate/templates/java/util_macros.templ
src/bin/ion/commands/generate/utils.rs
tests/cli.rs

This PR works on adding support for optional/required fields in a struct. (This PR only adds support for optional/required fields in Java, Rust support is still pending).
- [Adds changes for optional/required fields](https://github.com/amazon-ion/ion-cli/commit/98a3bb9f71f613490e95f5af951f18fc80478372)
* Adds utility method `target_type_as_optional` for adding optional
fields
* Add changes to the generator for using `FieldPresence` to specify if
the field is required or optional
* Adds `Copy` impl for `FieldPresence`
- [Adds java template changes to check for field presence](https://github.com/amazon-ion/ion-cli/commit/04a09abe17a2a5b923ee1e8f185bd5766649d72e)
- [Adds test cases for optional/required fields](https://github.com/amazon-ion/ion-cli/commit/ef0eed85978aeb2135ce6972fd8d147dbfd45 …

Adds changes for optional/required fields in Java code generation

---

Cargo.lock
Cargo.toml

#155 
Fixes #155 by pinning the `ion-rs` version.
My intention is to merge this into the `patch-v0.7.1` branch and release a patch version from that branch.
----

Pin ion-rs version to 1.0.0-rc.7; bump version to v0.7.1

---

Cargo.lock
Cargo.toml

This PR bumps the version to 0.9.0
----

Bumps version to 0.9.0

---

Cargo.lock
Cargo.toml
src/bin/ion/commands/inspect.rs

Fixes #162 
Update to latest release of `ion-rs` and bump to a new patch version
----

Update ion-rs dependency; bump version to 0.9.1

---

Cargo.lock
Cargo.toml

Version bump to v0.11.0
